# Dependencies
#markdown:            redcarpet
#highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'
      
# Setup
title:            RoetGer
tagline:          'Machine Intelligence, Statistics, and other stuff.'
description:      'Machine Intelligence, Statistics, and other stuff.'
url:              http://roetger.github.io

author:
  name:           RoetGer
  url:            http://roetger.github.io
  gravatar:       https://en.gravatar.com/yourname
  photo:          http://2.gravatar.com/avatar/00000000000000000000000000000000?size=350
  introduction:   '"Artificial intelligence will reach human levels by around 2029. Follow that out further to, say, 2045, we will have multiplied the intelligence, the human biological machine intelligence of our civilization a billion-fold." - Ray Kurzweil'

paginate:         5
paginate_path:    '/blog/page:num'

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/codinfox/roetger.github.io

# Puglins
#mathjax: true # whether support mathjax
google_analytics_token: 'UA-102234755-1' # leave blank if you don't want google analytics
disqus_short_name: 'roetger-github-io' # leave blank if you don't want disqus
