# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:            RoetGer
tagline:          'Machine Intelligence, Statistics, and other stuff.'
description:      'Machine Intelligence, Statistics, and other stuff.'
url:              http://roetger.github.io

author:
  name:           RoetGer
  url:            http://roetger.github.io
  gravatar:       https://en.gravatar.com/yourname
  photo:          http://2.gravatar.com/avatar/00000000000000000000000000000000?size=350
  introduction:   '“The question of whether a computer can think is no more interesting than the question of whether a submarine can swim.” 
			― Edsger W. Dijkstra'

paginate:         5
paginate_path:    '/blog/page:num'

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/codinfox/roetger.github.io

# Puglins
#mathjax: true # whether support mathjax
google_analytics_token: 'UA-102234755-1' # leave blank if you don't want google analytics
disqus_short_name: 'roetger-github-io.disqus.com/admin/' # leave blank if you don't want disqus
