# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:            Codinfox
tagline:          'Learning to be Giant.'
description:      'Machine Learning, Stats, and other stuff'
url:              http://codinfox.github.io

author:
  name:           RoetGer
  url:            http://roetger.github.io
  gravatar:       https://en.gravatar.com/yourname
  photo:          http://2.gravatar.com/avatar/00000000000000000000000000000000?size=350
  introduction:   'Machine Learning, Stats, and other stuff'
 
paginate:         5
paginate_path:    '/blog/page:num'

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/roetger/roetger.github.io
